### ISSUE TITLE
Port broken - Frontend for Photoprism no longer built: diff provided that remedies the issue

### ISSUE THREAD

**Issue by llmII** [huo-ju/photoprism-freebsd-port#36]
I ran poudriere with the latest here, and the result is an unworkable photoprism. It's looking for `/var/db/photoprism/assets/static/build/assets.json` and such does not exist. I did similarly a while ago for the January 6th version and that does have those in the build.

**Comment by llmII** [comment]
This diff fixes it: (pending verification, the build looks right though)

``` diff
diff --git a/Makefile b/Makefile
index 46aa041..ba2fe98 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ post-extract:
        @${REINPLACE_CMD} -e 's|sha1sum|shasum|g' ${WRKSRC}/scripts/download-nsfw.sh

 pre-build:
-       @${REINPLACE_CMD} -e 's|all: dep build-js|all: dep build-go|g' ${WRKSRC}/Makefile
+       @${REINPLACE_CMD} -e 's|all: dep build-js|all: dep build-go build-js|g' ${WRKSRC}/Makefile
        @${REINPLACE_CMD} -e 's|        go build -v ./...|      CGO_LDFLAGS="-L/usr/local/lib" go build -v ./cmd/... ./internal/... ./pkg/...|g' ${WRKSRC}/Makefile
        @${REINPLACE_CMD} -e 's|        scripts/build.sh debug| CGO_LDFLAGS="-L/usr/local/lib" scripts/build.sh debug|g' ${WRKSRC}/Makefile

diff --git a/files/pkg-install.in b/files/pkg-install.in
index 5781815..946a0fd 100644
--- a/files/pkg-install.in
+++ b/files/pkg-install.in
@@ -33,6 +33,6 @@ fi

 if [ "$2" = "POST-INSTALL" ]; then
        echo "${USER}:${GROUP} %%PHOTOPRISM_DATA_DIR%%"
-       chown -R ${USER}:${GROUP} %%PHOTOPRISM_DATA_DIR%%
+       #chown -R ${USER}:${GROUP} %%PHOTOPRISM_DATA_DIR%%
 fi

diff --git a/pkg-plist b/pkg-plist
index 94e0c4b..21d6ebb 100644
--- a/pkg-plist
+++ b/pkg-plist
@@ -593,6 +593,21 @@ bin/photoprism
 /var/db/photoprism/assets/static/brands/youtube-square.svg
 /var/db/photoprism/assets/static/brands/youtube.svg
 /var/db/photoprism/assets/static/brands/zhihu.svg
+/var/db/photoprism/assets/static/build/sw.js
+/var/db/photoprism/assets/static/build/0ff4d62150facee6b7de.png
+/var/db/photoprism/assets/static/build/assets.json
+/var/db/photoprism/assets/static/build/194d1b9ef54d0014b3c4.ttf
+/var/db/photoprism/assets/static/build/14d740b6ee64510747b0.gif
+/var/db/photoprism/assets/static/build/share.7b7be7e186ad53e98951.css
+/var/db/photoprism/assets/static/build/share.338c77bd0e5f5411cc90.js.LICENSE.txt
+/var/db/photoprism/assets/static/build/aef30bd507a35c7688c7.woff
+/var/db/photoprism/assets/static/build/app.6184d1cc21bc6c21a255.js.LICENSE.txt
+/var/db/photoprism/assets/static/build/app.6184d1cc21bc6c21a255.js
+/var/db/photoprism/assets/static/build/share.338c77bd0e5f5411cc90.js
+/var/db/photoprism/assets/static/build/c4dac66977e8a757a3ca.eot
+/var/db/photoprism/assets/static/build/1f0f6cdb23348c639cc5.woff2
+/var/db/photoprism/assets/static/build/app.7b7be7e186ad53e98951.css
+/var/db/photoprism/assets/static/build/f64c3af3d0d25b9e4e00.svg
 /var/db/photoprism/assets/static/font/Open Sans Bold/0-255.pbf
 /var/db/photoprism/assets/static/font/Open Sans Bold/1024-1279.pbf
 /var/db/photoprism/assets/static/font/Open Sans Bold/10240-10495.pbf
```

**Comment by gvelim** [comment]
Thanks for the pointers. I have made the changes and I got the following build error...
```
...
go: downloading github.com/go-playground/locales v0.14.0

> photoprism@1.0.0 build
> webpack --node-env=production

...
...

sh: webpack: not found
gmake[1]: *** [Makefile:161: build-js] Error 127gmake[1]: Leaving directory '/root/photoprism-freebsd-port/work/photoprism-0059f429edac04b3741bf3f85411ada686cf477f'
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** [do-build] Error code 1
```

Then I re-run `make -j8 package` without doing a `make clean` and `webpack` executed correctly

Now I have photoprism running as before.

Many thanks !!

**Comment by huo-ju** [comment]
@llmII Thanks for the patch! The bug has been fixed in 0e043740529c452fde173804cfa592cf8aba81b7

**Comment by Electr0Fi** [comment]
> @llmII Thanks for the patch! The bug has been fixed in [0e04374](https://github.com/huo-ju/photoprism-freebsd-port/commit/0e043740529c452fde173804cfa592cf8aba81b7)

Sorry, dumb question, but which commands do I need to run in order to rebuild Photoprism?

I've pulled the latest changed from the repository, then ran `make config` and `make && make install` but I still get the encounter the missing `assets.json` issue

**Comment by gvelim** [comment]
> Sorry, dumb question, but which commands do I need to run in order to rebuild Photoprism?

# make 
# make package
# make install

 I still get the above (see my message) build error the first time, but compiles successfully after I re-run `make package` (without make clean)

hope this helps

**Comment by Electr0Fi** [comment]
> > Sorry, dumb question, but which commands do I need to run in order to rebuild Photoprism?
> 
> ```
> # make 
> # make package
> # make install
> ```
> 
> I still get the above (see my message) build error the first time, but compiles successfully after I re-run `make package` (without make clean)
> 
> hope this helps

Okay, I ran those three commands but it tells me that Photoprism is already installed...

```
# make install
===>  Installing for photoprism-g20220302
===>  Checking if photoprism is already installed
===>   photoprism-g20220302 is already installed
      You may wish to ``make deinstall'' and install this port again
      by ``make reinstall'' to upgrade it properly.
      If you really wish to overwrite the old port of photoprism
      without deleting it first, set the variable "FORCE_PKG_REGISTER"
      in your environment or the "make install" command line.
*** Error code 1

Stop.
```

If it try `make deinstall` or `make reinstall` it just says it doesn't know how to do that.

**Comment by gvelim** [comment]
sorry my bad... it should read
```
# make 
# make package
# make reinstall
```

**Comment by Electr0Fi** [comment]
> ```
> # make 
> # make package
> # make reinstall
> ```

That did it! Thanks so much <3
