### ISSUE TITLE
libheif problem

### ISSUE THREAD

**Issue by vanyolai** [huo-ju/photoprism-freebsd-port#57]
After compiling the latest version, I got a message:
`photoprism-g20230506: "/usr/ports/graphics/libheif>=1.14.2" non-existent -- dependency list incomplete`
Since this version, transcoding is not working, too
libx264: failed transcoding and the filename. Am I missing something?
Thanks

**Comment by huo-ju** [comment]
Yes, the new version depends on libheif, and the latest libheif is 1.16.1 https://www.freshports.org/graphics/libheif/  You may need to update the port tree if there are no libheif>=1.14.2

**Comment by vanyolai** [comment]
I did a portsnap fetch/extract/update and
pkg search libheif result is
libheif-1.16.1                 ISO/IEC 23008-12:2017 HEIF file format de- and encoder
and this version is already installed on my system.

**Comment by jan666** [comment]
> libx264: failed transcoding and the filename. Am I missing something?

Check your ffmpeg version. I guess it's version 6. Version 6 is not supported by Photoprism. You need version 4.

**Comment by huo-ju** [comment]
Fixed in the new version. @vanyolai  Thanks for your report, and this version should fix your issue https://github.com/huo-ju/photoprism-freebsd-port/commit/08be75fb79fc6a69a765d2e9e037835e553f5aa8

**Comment by vanyolai** [comment]
> > libx264: failed transcoding and the filename. Am I missing something?
> 
> Check your ffmpeg version. I guess it's version 6. Version 6 is not supported by Photoprism. You need version 4.

After removing ffmpeg6 and installing ffmpeg4, the problem is still there. But when building photoprism, the make process is invoking ffmpeg6 again...

**Comment by vanyolai** [comment]
> Fixed in the new version. @vanyolai Thanks for your report, and this version should fix your issue [08be75f](https://github.com/huo-ju/photoprism-freebsd-port/commit/08be75fb79fc6a69a765d2e9e037835e553f5aa8)

Thank you, fix is confirmed.
